project:
  type: website
  output-dir: "2403"

website:
  title: "ddls-template-course"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - syllabus.qmd
      - trainers.qmd
      - section: "Materials"
        contents: materials/**/*
  navbar:
    background: "#A7C947"
    logo: "img/SciLifeLab_Logotype_NEG.png"
  favicon: "img/SciLifeLab_Logotype_NEG.png"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 400px
      body-width: 1600px
      margin-width: 200px
      gutter-width: 1.5rem
