project:
  type: website
  output-dir: docs

website:
  title: "ddls-training"
  sidebar:
    style: "floating"
    search: true
    contents: 
      - index.qmd 
      - trainers.qmd
      - section: "Materials"
        contents: materials/**/*

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

